### ISSUE TITLE
Nothing loads or appears. Anyone able to get this to work?

### ISSUE THREAD

**Issue by BerkSmash1984** [basti0001/MMM-iHaveBeenThere#7]
Completed the git clone in my MM modules directory and added my config. Nothing loads, however. I also do a npm install in case it was required. Same result. Here is my config (using this with MMM-Pages, hence the classes):

![image](https://github.com/basti0001/MMM-iHaveBeenThere/assets/104693081/53a26593-6245-4282-baa6-c035bd39d0f5)

Any ideas? I checked the dev console and MM logs and did not see anything.

**Comment by KristjanESPERANTO** [comment]
Please try if it works with my fork.

```js
cd ~/MagicMirror/modules
rm -r MMM-iHaveBeenThere
git clone https://github.com/KristjanESPERANTO/MMM-iHaveBeenThere
cd MMM-iHaveBeenThere
npm install
```

If it does not work. See if you can find anything unusual in the logs of node or the browser.

**Comment by BerkSmash1984** [comment]
Thanks @KristjanESPERANTO ! What is the MMM-ImagesPhotos module? Or did you mean to type cd MMM-iHaveBeenThere?

**Comment by KristjanESPERANTO** [comment]
Oh, copy paste issue. I fixed it.

**Comment by BerkSmash1984** [comment]
Appreciate you taking the time to help. Unfortunately, it is still not working for me. It is supposed to appear on page three but nothing is showing. I am not seeing any specific errors in the dev console either related to this module specifically:


![image](https://github.com/basti0001/MMM-iHaveBeenThere/assets/104693081/033a5e31-3bdb-4f05-9ea6-1d9200cb1fbc)


It does show it is resumed on page 3:

![image](https://github.com/basti0001/MMM-iHaveBeenThere/assets/104693081/6857363d-3b76-4ba2-b8a3-77fbf2f1d994)


Here is my config again, does anything stand out to you?

![image](https://github.com/basti0001/MMM-iHaveBeenThere/assets/104693081/55a0cb0b-3ed0-43af-899f-96467791aa49)

**Comment by BerkSmash1984** [comment]
So this is interesting, once I added Header for the module to the config, it started to work:
![image](https://github.com/basti0001/MMM-iHaveBeenThere/assets/104693081/639b6fd8-9004-46fd-b534-7a2aeff1bddc)

![image](https://github.com/basti0001/MMM-iHaveBeenThere/assets/104693081/37f4413f-89f3-4852-8077-05cb63176f87)


This is obv redundant with the title also listed as a config option. Also, it is very small so will need to play with the size in the zoom options and custom.css

**Comment by BerkSmash1984** [comment]
Looks like this is really meant to be in one of the larger positions, such as middle center. Will need to shuffle some modules around, but it is working now. Thanks for your help @KristjanESPERANTO !

![image](https://github.com/basti0001/MMM-iHaveBeenThere/assets/104693081/0da3b696-56a8-4be4-bb85-56d23d375d42)

**Comment by BerkSmash1984** [comment]
@KristjanESPERANTO  Maybe I spoke too soon. The above screenshots were from a browser from my computer for testing, but on my RPI4 itself, the module doesn't display every time, and when it does, it gets all jumbled or the map flashes like crazy:

![image](https://github.com/basti0001/MMM-iHaveBeenThere/assets/104693081/05433745-11b2-41e0-8989-bcdc3c1d73f7)

I am using pm2 but can get the behavior to occur by also launching a browser in Fullscreen mode with my MM IP specified both in Chromium and Midori. On Browsers outside of my RPI4, the module works fine every time.  Any ideas? This is very odd.

**Comment by KristjanESPERANTO** [comment]
Shot into the blue: Please try `export ELECTRON_ENABLE_GPU=1 && npm run start` instead of `npm run start` to start the mirror.

**Comment by BerkSmash1984** [comment]
Gave it a go, but same result:

![image](https://github.com/basti0001/MMM-iHaveBeenThere/assets/104693081/b512d207-65b9-4229-ae3b-5af98429e54b)

**Comment by KristjanESPERANTO** [comment]
What a pity. As the issue does not occur on my system, I am running out of ideas.

Are you using an up-to-date system (operating system, node, npm, MagicMirror)?

I have another approach, but it requires a few JavaScript skills: The main package used to display the maps is [amCharts](https://www.amcharts.com/). Version 3 is used in the module, but there is now version 5, which should also contain some performance improvements. However, there have been some changes to how the package is used, and the module would have to be adapted. I have not found a quick way to do that and I am currently investing my time in other projects.

**Comment by BerkSmash1984** [comment]
Yes the system (RPI4) is completely up to date as is npm, the mm, etc,. Everything else is working on the MM, so this is odd. I really appreciate you taking the time to help. For now, I have disabled the module

**Comment by COlson28** [comment]
Came here after also having issues getting it to appear. 

The map flashes up on launch, then disappears and never comes back. 

Interestingly, when I disable the MMM-Pages module (and other related modules) it does come up fine, all other settings the same. So some sort of issue when displayed by MMM-Pages perhaps?
